image: Visual Studio 2017
configuration: Release

install:
  ## Prepare .sln with cmake
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir cmake_build
  - cd cmake_build
  - cmake --version
  - find_package(SDL2 REQUIRED)
  - include_directories(${SDL2_INCLUDE_DIR})
  - cmake c:\projects\yquake2

build_script: msbuild "C:\projects\yquake2\cmake_build\yquake2.sln"

artifacts:
 - path: cmake_build\Release\**\*.*
